### ISSUE TITLE
LPDC(1440,1056) and LDPC(1440,1344). Can anyone tell me how to find or make the H- and G-Matrix for LDPC-coding ?

### ISSUE THREAD

**Issue by IhabAdarbeh** [Barkhausen-Institut/hermespy#21]
from copy import deepcopy
from hermespy.core import ConsoleMode, dB
import numpy as np
from hermespy.channel import Channel, IdealChannel
from hermespy.fec.aff3ct import TurboCoding, BCHCoding, ReedSolomonCoding, LDPCCoding
from hermespy.tools import db2lin
from hermespy.simulation import Simulation
from hermespy.modem import RootRaisedCosineWaveform
from hermespy.modem import TransmittingModem, ReceivingModem, OFDMWaveform, GridResource, GridElement, SymbolSection, BitErrorEvaluator, BlockErrorEvaluator, FrameErrorEvaluator, ThroughputEvaluator

simulation = Simulation()
num_iterations = 20
h_source_path = "C:\\Users\\adaiha\\Desktop\\Hermespy\\H_matrix_1344_1440.alist"
g_save_path = "C:\\Users\\adaiha\\Desktop\\Hermespy\\g_matrix.alist"   
enable_syndrome_checking = True
min_num_iterations = 10
ldpc_coder = LDPCCoding(num_iterations, h_source_path,
                        g_save_path, enable_syndrome_checking, min_num_iterations)

data_block_size=1344
tx_device = simulation.new_device()
rx_device = simulation.new_device()
data = np.random.randint(0, 2, data_block_size)
waveform = RootRaisedCosineWaveform(modulation_order=16, oversampling_factor=2, num_preamble_symbols=0, num_data_symbols=100, symbol_rate=1e9)

tx_modem = TransmittingModem()
tx_modem.random_bits = data
tx_modem.encoder_manager.add_encoder(ldpc_coder)
tx_modem.waveform = deepcopy(waveform) 
tx_device.transmitters.add(tx_modem)

channel = IdealChannel()
simulation.scenario.set_channel(tx_device, rx_device, channel)

rx_modem = ReceivingModem()
rx_modem.waveform = deepcopy(waveform)
rx_modem.encoder_manager.add_encoder(ldpc_coder)
rx_device.receivers.add(rx_modem)

simulation.new_dimension('noise_level', dB(0, 2), rx_device)
simulation.add_evaluator(BitErrorEvaluator(tx_modem, rx_modem))
simulation.num_samples, simulation.min_num_samples = 10000, 9000
simulation.plot_results = True
simulation.num_actors = 2
simulation.results_dir = simulation.default_results_dir()

simulation.run()

**Comment by adlerjan** [comment]
The H files are part of the aff3ct library, to which HermesPy links with the LDPC class you're using.

Installing HermesPy from PyPi should also install a copy of all config files within the share directory of your Python environment, however, it is sometimes tricky to figure out where exactly on your filesystem it is located.
The easier option would be to download whatever you want to use directly from their repository https://github.com/aff3ct/configuration_files/tree/9d7257598885dc49b950b963893f86fa710f3104/dec/LDPC .

Qucik disclaimer: I was attempting to configure the LDPC class to give you an example, however, most runs result in a C++ error for me.
If it's the same on your system, I'll open a separate issue for this. Other links such as polar and turbo codes work just fine.

**Comment by IhabAdarbeh** [comment]
Thank you for your response and insights. I’ve tried the same approach, but unfortunately, I also encountered errors while working with the LDPC class in HermesPy. I even generated the matrices myself using the pyldpc library, but this led to errors as well.

I’ve tested other encoders and decoders, such as Polar and Turbo codes, which worked perfectly. However, LDPC is the most relevant for my bachelor’s thesis, and I need it to function properly.

Do you have any recommendations or workarounds for these issues? Alternatively, would it make sense to open a separate issue to investigate this further?
