### ISSUE TITLE
No module named 'hermespy.tools'

### ISSUE THREAD

**Issue by Xiwen-Lu** [Barkhausen-Institut/hermespy#5]
I just finish install the hermespy by `pip install hermespy`, but when i try to import it, it reminds me this.
All the traceback can be seen as below:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_349891/3690703635.py in <module>
      1 import matplotlib.pyplot as plt
----> 2 from hermespy import Scenario, Transmitter
      3 from hermespy.modem import WaveformGeneratorPskQam

~/Software/anaconda3/envs/pytorch/lib/python3.9/site-packages/hermespy/__init__.py in <module>
----> 1 from .channel import Channel
      2 from .modem import Transmitter, Receiver, WaveformGeneratorOfdm, WaveformGeneratorPskQam, WaveformGeneratorChirpFsk
      3 from .scenario import Scenario
      4 from .signal import Signal
      5 from .simulator_core import Simulation, HardwareLoop

~/Software/anaconda3/envs/pytorch/lib/python3.9/site-packages/hermespy/channel/__init__.py in <module>
      3 from .multipath_fading_channel import MultipathFadingChannel
      4 from .multipath_fading_templates import MultipathFadingCost256, MultipathFading5GTDL, MultipathFadingExponential
----> 5 from .radar_channel import RadarChannel
      6 
      7 __author__ = "Tobias Kronauer"

~/Software/anaconda3/envs/pytorch/lib/python3.9/site-packages/hermespy/channel/radar_channel.py in <module>
      9 
     10 from hermespy.channel import Channel
---> 11 from hermespy.tools import db2lin, lin2db, DbConversionType
     12 
     13 __author__ = "Andre Noll Barreto"

ModuleNotFoundError: No module named 'hermespy.tools'

**Comment by Xiwen-Lu** [comment]
OK, then i try to install it by souce code, it success

**Comment by adlerjan** [comment]
Hey, thanks for checking out Hermes and reporting a bug.

Looking at your message and the PyPi package, an error during packaging seems to have occured resulting in some modules missing in the final package wheel. It should be fixed with the latest patch!
