### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by nimamox** [Barkhausen-Institut/hermespy#9]
Is the project dead or is it still maintained? The notebook can not be opened on Google Colab. I tried to build it on Colab, Linux, and macOS and all failed.

**Comment by adlerjan** [comment]
The project is very much alive, this repository is primarily a public mirror that's being updated on a bi-anual basis.
I suspect that the issue might be that the notebooks are tracked with git lfs?

**Comment by adlerjan** [comment]
@nimamox I gave it a try with the FEC example, manually downloading and uploading to CoLabs works just fine: https://colab.research.google.com/drive/1A_fJKEntoOANRTQf8d2r3l5tO-0u9Tdy?usp=sharing

Could you give me some more details about the issues you're having?
